"use client";
import Head from "next/head";
import { Flex, Heading } from "@chakra-ui/react";

export default function Home() {
  return (
    <div>
      <Head>
        <title>My Digital Garden</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Flex minH="100vh" align="center" justify="center">
          <Heading>The Future Location of My Digital Greenhouse 🌱</Heading>
        </Flex>
      </main>
    </div>
  );
}
